In [32]:
import numpy as np
import pandas as pd

In [33]:
#df = pd.read_csv('data.csv')
df2 = pd.read_csv('kaggle-data.csv',low_memory=False)

In [34]:

df2

,ID,md5,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,...,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate,Unnamed: 57
0,1,b69acb3bb133974e48229627663f96d4,332,224,8450,8.0,0,16896,8192,0,...,3.492126,3.492126,3.492126,864.000000,864.0,864,72,0,1,NaN
1,2,1cbee4b3725629bd0aa6ac2ff500925f,332,224,258,9.0,0,84480,25600,0,...,3.486827,3.486827,3.486827,892.000000,892.0,892,72,0,1,NaN
2,3,b7027cf0cd31c820928950cbfe7e91ef,332,224,8450,8.0,0,4608,3584,0,...,3.517270,3.517270,3.517270,952.000000,952.0,952,72,0,1,NaN
3,4,156a0bb069f94d1e7c2508318805f2a4,332,224,8450,10.0,0,108544,15872,0,...,3.270559,3.034188,3.506931,1032.000000,972.0,1092,72,0,1,NaN
4,5,c72bf851fed5542abba904b1f3944cd5,332,224,8226,48.0,0,513024,2048,0,...,3.420977,3.420977,3.420977,954.000000,954.0,954,0,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216347,216348,8e292b418568d6e7b87f2a32aee7074b,332,224,258,11.0,0,205824,223744,0,...,4.122736,1.370260,7.677091,14900.714286,16.0,81654,72,0,0,NaN
216348,216349,260d9e2258aed4c8a3bbd703ec895822,332,224,33167,2.0,25,37888,185344,0,...,3.377663,2.031619,5.050074,6905.846154,44.0,67624,0,15,0,NaN
216349,216350,8d088a51b7d225c9f5d11d239791ec3f,332,224,258,10.0,0,118272,380416,0,...,6.825406,2.617026,7.990487,14981.909091,48.0,22648,72,14,0,NaN
216350,216351,4286dccf67ca220fe67635388229a9f3,332,224,33166,2.0,25,49152,16896,0,...,3.421627,2.060964,4.739744,601.600000,16.0,2216,0,0,0,NaN
216351,216352,d7648eae45f09b3adb75127f43be6d11,332,224,258,11.0,0,111616,468480,0,...,4.407252,1.980482,6.115374,96625.000000,20.0,318464,72,0,0,NaN

In [35]:
df2.max()

ID                                             216352
md5                                           pdf.exe
Machine                                           512
SizeOfOptionalHeader                              352
Characteristics                                 49551
MajorLinkerVersion                            33166.0
MinorLinkerVersion                                255
SizeOfCode                                 4294967295
SizeOfInitializedData                      4294967295
SizeOfUninitializedData                    4294967295
AddressOfEntryPoint                        4127916100
BaseOfCode                                 2712128608
BaseOfData                                 1920746335
ImageBase                      18446735277616500736.0
SectionAlignment                            134217728
FileAlignment                                   65536
MajorOperatingSystemVersion                     49850
MinorOperatingSystemVersion                     63323
MajorImageVersion                               64416
MinorImageVersion                               64148
MajorSubsystemVersion                              10
MinorSubsystemVersion                           47600
SizeOfImage                                1410035712
SizeOfHeaders                                 1118208
CheckSum                                   4294967295
Subsystem                                          16
DllCharacteristics                              53600
SizeOfStackReserve                     17592187092992
SizeOfStackCommit                      17592187092992
SizeOfHeapReserve                         68719476736
SizeOfHeapCommit                           2077323491
LoaderFlags                                3098696260
NumberOfRvaAndSizes                        3402309701
SectionsNb                                         97
SectionsMeanEntropy                               8.0
SectionsMinEntropy                           7.998564
SectionsMaxEntropy                           7.999994
SectionsMeanRawsize                     1431641941.33
SectionsMinRawsize                           29000704
SectionMaxRawsize                          4294958080
SectionsMeanVirtualsize                  1431673348.0
SectionsMinVirtualsize                     29000672.0
SectionMaxVirtualsize                      4294884876
ImportsNbDLL                                   338600
ImportsNb                                        7375
ImportsNbOrdinal                                 3450
ExportNb                                        23986
ResourcesNb                                      8215
ResourcesMeanEntropy                            143.0
ResourcesMinEntropy                          7.999723
ResourcesMaxEntropy                               8.0
ResourcesMeanSize                        4294902692.0
ResourcesMinSize                         4294902692.0
ResourcesMaxSize                           4294902692
LoadConfigurationSize                      4294967294
VersionInformationSize                             26
legitimate                                          1
Unnamed: 57                                       0.0
dtype: object

In [36]:
dataF = pd.DataFrame(df2)

In [37]:
dataF

,ID,md5,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,...,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate,Unnamed: 57
0,1,b69acb3bb133974e48229627663f96d4,332,224,8450,8.0,0,16896,8192,0,...,3.492126,3.492126,3.492126,864.000000,864.0,864,72,0,1,NaN
1,2,1cbee4b3725629bd0aa6ac2ff500925f,332,224,258,9.0,0,84480,25600,0,...,3.486827,3.486827,3.486827,892.000000,892.0,892,72,0,1,NaN
2,3,b7027cf0cd31c820928950cbfe7e91ef,332,224,8450,8.0,0,4608,3584,0,...,3.517270,3.517270,3.517270,952.000000,952.0,952,72,0,1,NaN
3,4,156a0bb069f94d1e7c2508318805f2a4,332,224,8450,10.0,0,108544,15872,0,...,3.270559,3.034188,3.506931,1032.000000,972.0,1092,72,0,1,NaN
4,5,c72bf851fed5542abba904b1f3944cd5,332,224,8226,48.0,0,513024,2048,0,...,3.420977,3.420977,3.420977,954.000000,954.0,954,0,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216347,216348,8e292b418568d6e7b87f2a32aee7074b,332,224,258,11.0,0,205824,223744,0,...,4.122736,1.370260,7.677091,14900.714286,16.0,81654,72,0,0,NaN
216348,216349,260d9e2258aed4c8a3bbd703ec895822,332,224,33167,2.0,25,37888,185344,0,...,3.377663,2.031619,5.050074,6905.846154,44.0,67624,0,15,0,NaN
216349,216350,8d088a51b7d225c9f5d11d239791ec3f,332,224,258,10.0,0,118272,380416,0,...,6.825406,2.617026,7.990487,14981.909091,48.0,22648,72,14,0,NaN
216350,216351,4286dccf67ca220fe67635388229a9f3,332,224,33166,2.0,25,49152,16896,0,...,3.421627,2.060964,4.739744,601.600000,16.0,2216,0,0,0,NaN
216351,216352,d7648eae45f09b3adb75127f43be6d11,332,224,258,11.0,0,111616,468480,0,...,4.407252,1.980482,6.115374,96625.000000,20.0,318464,72,0,0,NaN

In [38]:
dataF.index += 1

In [39]:
dataF

,ID,md5,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,...,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate,Unnamed: 57
1,1,b69acb3bb133974e48229627663f96d4,332,224,8450,8.0,0,16896,8192,0,...,3.492126,3.492126,3.492126,864.000000,864.0,864,72,0,1,NaN
2,2,1cbee4b3725629bd0aa6ac2ff500925f,332,224,258,9.0,0,84480,25600,0,...,3.486827,3.486827,3.486827,892.000000,892.0,892,72,0,1,NaN
3,3,b7027cf0cd31c820928950cbfe7e91ef,332,224,8450,8.0,0,4608,3584,0,...,3.517270,3.517270,3.517270,952.000000,952.0,952,72,0,1,NaN
4,4,156a0bb069f94d1e7c2508318805f2a4,332,224,8450,10.0,0,108544,15872,0,...,3.270559,3.034188,3.506931,1032.000000,972.0,1092,72,0,1,NaN
5,5,c72bf851fed5542abba904b1f3944cd5,332,224,8226,48.0,0,513024,2048,0,...,3.420977,3.420977,3.420977,954.000000,954.0,954,0,0,1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216348,216348,8e292b418568d6e7b87f2a32aee7074b,332,224,258,11.0,0,205824,223744,0,...,4.122736,1.370260,7.677091,14900.714286,16.0,81654,72,0,0,NaN
216349,216349,260d9e2258aed4c8a3bbd703ec895822,332,224,33167,2.0,25,37888,185344,0,...,3.377663,2.031619,5.050074,6905.846154,44.0,67624,0,15,0,NaN
216350,216350,8d088a51b7d225c9f5d11d239791ec3f,332,224,258,10.0,0,118272,380416,0,...,6.825406,2.617026,7.990487,14981.909091,48.0,22648,72,14,0,NaN
216351,216351,4286dccf67ca220fe67635388229a9f3,332,224,33166,2.0,25,49152,16896,0,...,3.421627,2.060964,4.739744,601.600000,16.0,2216,0,0,0,NaN
216352,216352,d7648eae45f09b3adb75127f43be6d11,332,224,258,11.0,0,111616,468480,0,...,4.407252,1.980482,6.115374,96625.000000,20.0,318464,72,0,0,NaN

In [40]:
dataF.pop(dataF.columns[-1])
#deleted nan column

1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
          ..
216348   NaN
216349   NaN
216350   NaN
216351   NaN
216352   NaN
Name: Unnamed: 57, Length: 216352, dtype: float64

In [41]:
dataF

,ID,md5,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,...,ResourcesNb,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate
1,1,b69acb3bb133974e48229627663f96d4,332,224,8450,8.0,0,16896,8192,0,...,1,3.492126,3.492126,3.492126,864.000000,864.0,864,72,0,1
2,2,1cbee4b3725629bd0aa6ac2ff500925f,332,224,258,9.0,0,84480,25600,0,...,1,3.486827,3.486827,3.486827,892.000000,892.0,892,72,0,1
3,3,b7027cf0cd31c820928950cbfe7e91ef,332,224,8450,8.0,0,4608,3584,0,...,1,3.517270,3.517270,3.517270,952.000000,952.0,952,72,0,1
4,4,156a0bb069f94d1e7c2508318805f2a4,332,224,8450,10.0,0,108544,15872,0,...,2,3.270559,3.034188,3.506931,1032.000000,972.0,1092,72,0,1
5,5,c72bf851fed5542abba904b1f3944cd5,332,224,8226,48.0,0,513024,2048,0,...,1,3.420977,3.420977,3.420977,954.000000,954.0,954,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216348,216348,8e292b418568d6e7b87f2a32aee7074b,332,224,258,11.0,0,205824,223744,0,...,7,4.122736,1.370260,7.677091,14900.714286,16.0,81654,72,0,0
216349,216349,260d9e2258aed4c8a3bbd703ec895822,332,224,33167,2.0,25,37888,185344,0,...,26,3.377663,2.031619,5.050074,6905.846154,44.0,67624,0,15,0
216350,216350,8d088a51b7d225c9f5d11d239791ec3f,332,224,258,10.0,0,118272,380416,0,...,22,6.825406,2.617026,7.990487,14981.909091,48.0,22648,72,14,0
216351,216351,4286dccf67ca220fe67635388229a9f3,332,224,33166,2.0,25,49152,16896,0,...,10,3.421627,2.060964,4.739744,601.600000,16.0,2216,0,0,0
216352,216352,d7648eae45f09b3adb75127f43be6d11,332,224,258,11.0,0,111616,468480,0,...,4,4.407252,1.980482,6.115374,96625.000000,20.0,318464,72,0,0

In [42]:
dataF['TotalSize']= dataF['SizeOfCode']+dataF['SizeOfImage'] #adding new column totalsize adding by adding values

In [43]:
dataF

,ID,md5,Machine,SizeOfOptionalHeader,Characteristics,MajorLinkerVersion,MinorLinkerVersion,SizeOfCode,SizeOfInitializedData,SizeOfUninitializedData,...,ResourcesMeanEntropy,ResourcesMinEntropy,ResourcesMaxEntropy,ResourcesMeanSize,ResourcesMinSize,ResourcesMaxSize,LoadConfigurationSize,VersionInformationSize,legitimate,TotalSize
1,1,b69acb3bb133974e48229627663f96d4,332,224,8450,8.0,0,16896,8192,0,...,3.492126,3.492126,3.492126,864.000000,864.0,864,72,0,1,57856
2,2,1cbee4b3725629bd0aa6ac2ff500925f,332,224,258,9.0,0,84480,25600,0,...,3.486827,3.486827,3.486827,892.000000,892.0,892,72,0,1,211456
3,3,b7027cf0cd31c820928950cbfe7e91ef,332,224,8450,8.0,0,4608,3584,0,...,3.517270,3.517270,3.517270,952.000000,952.0,952,72,0,1,29184
4,4,156a0bb069f94d1e7c2508318805f2a4,332,224,8450,10.0,0,108544,15872,0,...,3.270559,3.034188,3.506931,1032.000000,972.0,1092,72,0,1,251904
5,5,c72bf851fed5542abba904b1f3944cd5,332,224,8226,48.0,0,513024,2048,0,...,3.420977,3.420977,3.420977,954.000000,954.0,954,0,0,1,1053696
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216348,216348,8e292b418568d6e7b87f2a32aee7074b,332,224,258,11.0,0,205824,223744,0,...,4.122736,1.370260,7.677091,14900.714286,16.0,81654,72,0,0,648192
216349,216349,260d9e2258aed4c8a3bbd703ec895822,332,224,33167,2.0,25,37888,185344,0,...,3.377663,2.031619,5.050074,6905.846154,44.0,67624,0,15,0,291840
216350,216350,8d088a51b7d225c9f5d11d239791ec3f,332,224,258,10.0,0,118272,380416,0,...,6.825406,2.617026,7.990487,14981.909091,48.0,22648,72,14,0,634368
216351,216351,4286dccf67ca220fe67635388229a9f3,332,224,33166,2.0,25,49152,16896,0,...,3.421627,2.060964,4.739744,601.600000,16.0,2216,0,0,0,139264
216352,216352,d7648eae45f09b3adb75127f43be6d11,332,224,258,11.0,0,111616,468480,0,...,4.407252,1.980482,6.115374,96625.000000,20.0,318464,72,0,0,705536

In [44]:
dataF = dataF.reindex(sorted(dataF.columns), axis=1) #sorting the columns by aplhabetical order

In [45]:
dataF

,AddressOfEntryPoint,BaseOfCode,BaseOfData,Characteristics,CheckSum,DllCharacteristics,ExportNb,FileAlignment,ID,ImageBase,...,SizeOfInitializedData,SizeOfOptionalHeader,SizeOfStackCommit,SizeOfStackReserve,SizeOfUninitializedData,Subsystem,TotalSize,VersionInformationSize,legitimate,md5
1,16947,4096,24576,8450,84427,320,31,512,1,4194304.0,...,8192,224,4096,262144,0,2,57856,0,1,b69acb3bb133974e48229627663f96d4
2,10973,4096,90112,258,180181,320,2,512,2,65536.0,...,25600,224,4096,65536,0,9,211456,0,1,1cbee4b3725629bd0aa6ac2ff500925f
3,6452,4096,12288,8450,10208,320,3,512,3,264962048.0,...,3584,224,4096,262144,0,2,29184,0,1,b7027cf0cd31c820928950cbfe7e91ef
4,105021,4096,114688,8450,165754,320,105,512,4,268435456.0,...,15872,224,4096,1048576,0,3,251904,0,1,156a0bb069f94d1e7c2508318805f2a4
5,520922,8192,524288,8226,582537,34144,0,512,5,268435456.0,...,2048,224,4096,1048576,0,3,1053696,0,1,c72bf851fed5542abba904b1f3944cd5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216348,123291,4096,212992,258,0,33088,0,512,216348,4194304.0,...,223744,224,4096,1048576,0,2,648192,0,0,8e292b418568d6e7b87f2a32aee7074b
216349,40000,4096,45056,33167,0,32768,0,512,216349,4194304.0,...,185344,224,16384,1048576,0,2,291840,15,0,260d9e2258aed4c8a3bbd703ec895822
216350,59610,4096,122880,258,515385,33088,0,512,216350,4194304.0,...,380416,224,4096,1048576,0,2,634368,14,0,8d088a51b7d225c9f5d11d239791ec3f
216351,51216,4096,53248,33166,0,0,0,512,216351,4194304.0,...,16896,224,16384,1048576,0,2,139264,0,0,4286dccf67ca220fe67635388229a9f3
216352,22731,4096,118784,258,2018448048,33088,0,512,216352,4194304.0,...,468480,224,4096,1048576,0,2,705536,0,0,d7648eae45f09b3adb75127f43be6d11

In [46]:
fila = np.random.randint(300000,2500000,size=(58))
fila

array([1875627, 1598312,  886301,  812202, 1476812, 2008820, 2486940,
       1863932, 1524784,  311746, 1898077, 1330109,  744023, 1828102,
       1249802,  934357, 1258533, 1731821, 1814367, 1215164, 1097000,
       2382527, 1687010, 1825825,  373949, 1856440,  773811, 2069083,
       2023511, 1764375, 1360588,  742094, 2193144, 2089869, 1198415,
        985515, 1315403,  505403,  770018, 1448924, 1163981, 1419095,
        729684, 1135548, 1335498, 2413795, 1180393,  733692, 1860004,
       2050699, 1359020, 1557018, 1617024, 1550363, 1605588, 1532483,
       1021471,  622367])

In [47]:
dataF.loc[len(dataF)+1] = fila #adding one row to the dataframe

In [48]:
dataF

,AddressOfEntryPoint,BaseOfCode,BaseOfData,Characteristics,CheckSum,DllCharacteristics,ExportNb,FileAlignment,ID,ImageBase,...,SizeOfInitializedData,SizeOfOptionalHeader,SizeOfStackCommit,SizeOfStackReserve,SizeOfUninitializedData,Subsystem,TotalSize,VersionInformationSize,legitimate,md5
1,16947,4096,24576,8450,84427,320,31,512,1,4194304.0,...,8192,224,4096,262144,0,2,57856,0,1,b69acb3bb133974e48229627663f96d4
2,10973,4096,90112,258,180181,320,2,512,2,65536.0,...,25600,224,4096,65536,0,9,211456,0,1,1cbee4b3725629bd0aa6ac2ff500925f
3,6452,4096,12288,8450,10208,320,3,512,3,264962048.0,...,3584,224,4096,262144,0,2,29184,0,1,b7027cf0cd31c820928950cbfe7e91ef
4,105021,4096,114688,8450,165754,320,105,512,4,268435456.0,...,15872,224,4096,1048576,0,3,251904,0,1,156a0bb069f94d1e7c2508318805f2a4
5,520922,8192,524288,8226,582537,34144,0,512,5,268435456.0,...,2048,224,4096,1048576,0,3,1053696,0,1,c72bf851fed5542abba904b1f3944cd5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216349,40000,4096,45056,33167,0,32768,0,512,216349,4194304.0,...,185344,224,16384,1048576,0,2,291840,15,0,260d9e2258aed4c8a3bbd703ec895822
216350,59610,4096,122880,258,515385,33088,0,512,216350,4194304.0,...,380416,224,4096,1048576,0,2,634368,14,0,8d088a51b7d225c9f5d11d239791ec3f
216351,51216,4096,53248,33166,0,0,0,512,216351,4194304.0,...,16896,224,16384,1048576,0,2,139264,0,0,4286dccf67ca220fe67635388229a9f3
216352,22731,4096,118784,258,2018448048,33088,0,512,216352,4194304.0,...,468480,224,4096,1048576,0,2,705536,0,0,d7648eae45f09b3adb75127f43be6d11
216353,1875627,1598312,886301,812202,1476812,2008820,2486940,1863932,1524784,311746.0,...,1860004,2050699,1359020,1557018,1617024,1550363,1605588,1532483,1021471,622367

In [50]:
dataF.sort_values(by=['TotalSize']) #ordering the dataframe by totalsize

,AddressOfEntryPoint,BaseOfCode,BaseOfData,Characteristics,CheckSum,DllCharacteristics,ExportNb,FileAlignment,ID,ImageBase,...,SizeOfInitializedData,SizeOfOptionalHeader,SizeOfStackCommit,SizeOfStackReserve,SizeOfUninitializedData,Subsystem,TotalSize,VersionInformationSize,legitimate,md5
55691,0,0,0,8193,0,0,0,512,55691,4194304.0,...,0,224,0,0,0,0,0,0,0,63c5de50c8ed7b426c8243800f46b1a2
49237,0,0,0,8193,0,0,0,512,49237,4194304.0,...,0,224,0,0,0,0,0,0,0,e7f970b88e9f92ed89ee84e0a9418985
41964,0,338028,4096,224,1024,2,0,4096,41964,339968.0,...,334336,332,1048576,0,440320,0,25,0,0,pdf.exe
179556,448,448,512,302,0,0,0,64,179556,65536.0,...,128,224,4096,262144,0,1,640,0,0,d98d341fa2d36e63e7d844fe42dd23ad
35430,448,448,512,302,0,0,0,64,35430,65536.0,...,128,224,4096,262144,0,1,640,0,0,904f2e098416c3fb1a13d903576ddf10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56677,7168,4096,16384,8450,2967351217,34112,42,4096,56677,4194304.0,...,688128,224,4096,1048576,0,3,1790394190,0,0,41cf55d6e0bfaff0785f1301e9fd7a70
47793,7168,4096,16384,8450,2967351217,34112,15,4096,47793,4194304.0,...,712704,224,4096,1048576,0,3,1790418766,0,0,c0db1584d7e496fed0b0dfe749325f90
177413,150560,2028711251,57344,271,61686,0,0,512,177413,4194304.0,...,1680749107,224,4096,1048576,27756,2,1818852978,17,0,7a7ed710a0cefd694f0c513fdaaf8473
45511,187374,4096,4096,258,0,33088,0,4096,45511,4194304.0,...,16384,224,4096,1048576,4294967295,2,4295192575,0,0,a17d2f7b275fcf9c41f341f8315e0460
37717,188130,4096,4096,258,0,33088,0,4096,37717,4194304.0,...,16384,224,4096,1048576,4294967295,2,4295192575,0,0,0c6c5e827771dbf6124209e6fb0b3de0