In [1]:
Panda series

SyntaxError: invalid syntax (3517090353.py, line 1)

In [5]:
import numpy as np
import pandas as pd

In [14]:
data1 =[1,2,3,4,"hola"]

In [15]:
dataS = pd.Series(data1)

In [16]:
dataS

0       1
1       2
2       3
3       4
4    hola
dtype: object

In [13]:
dataS.index

RangeIndex(start=0, stop=4, step=1)

In [18]:
dataR = np.random.rand(10000)

In [22]:
%timeit sum(dataR)

695 µs ± 7.06 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

In [23]:
%timeit np.sum(dataR)

4.6 µs ± 39.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)

In [24]:
dataS.index = ["Primero","segundo","tercero","cuarto","quinto"]

In [25]:
dataS

Primero       1
segundo       2
tercero       3
cuarto        4
quinto     hola
dtype: object

In [30]:
data2 = {'nombre':['Luis','Miguel','Pedro'],
        'id':['801000020','801000021','801000022'],
        'gpa':[3.80,4.00,3.99] }

In [31]:
data2

{'nombre': ['Luis', 'Miguel', 'Pedro'],
 'id': ['801000020', '801000021', '801000022'],
 'gpa': [3.8, 4.0, 3.99]}

In [32]:
dataF = pd.DataFrame(data2)

In [33]:
dataF

   nombre         id   gpa
0    Luis  801000020  3.80
1  Miguel  801000021  4.00
2   Pedro  801000022  3.99

In [63]:
dataF.sort_values(dataF, by = 'nombre')

TypeError: sort_values() got multiple values for argument 'by'

In [34]:
dataF.index += 1

In [35]:
dataF

   nombre         id   gpa
1    Luis  801000020  3.80
2  Miguel  801000021  4.00
3   Pedro  801000022  3.99

In [36]:
matx = np.random.rand(5,8)

In [48]:
 np.savetxt("jupyter/data3.csv", matx)

In [49]:
data3 = np.loadtxt("jupyter/data3.csv")

In [52]:
data3

array([[0.6595928 , 0.7100672 , 0.18518559, 0.38114723, 0.4956687 ,
        0.98215481, 0.20184067, 0.12946689],
       [0.68040366, 0.32891935, 0.19996393, 0.12422262, 0.34264305,
        0.16481267, 0.56614039, 0.40167734],
       [0.20266478, 0.86586669, 0.47463046, 0.00742947, 0.73526504,
        0.25779451, 0.25963731, 0.18850704],
       [0.0387881 , 0.34746691, 0.73046799, 0.14894617, 0.01764354,
        0.71769897, 0.89120899, 0.20920022],
       [0.55180989, 0.00889509, 0.67415659, 0.83702011, 0.41277905,
        0.79579599, 0.1764008 , 0.56652198]])

In [55]:
datad2 = pd.read_csv("jupyter/data3.csv")

In [56]:
datad2

  6.595927950576663257e-01 7.100672034166385371e-01 1.851855946455592816e-01 3.811472265202827669e-01 4.956687014457857865e-01 9.821548148403390632e-01 2.018406704423522102e-01 1.294668920432036074e-01
0  6.804036590234535664e-01 3.289193529250904469e...
1  2.026647848608045255e-01 8.658666924103116669e...
2  3.878810295822809895e-02 3.474669120711457726e...
3  5.518098873342722754e-01 8.895093090465988617e...

In [57]:
dataF2 = pd.DataFrame(data3,columns = ["largo","ancho","prof","alt","masa","radio","vol","dens"])

In [58]:
dataF2

,largo,ancho,prof,alt,masa,radio,vol,dens
0,0.659593,0.710067,0.185186,0.381147,0.495669,0.982155,0.201841,0.129467
1,0.680404,0.328919,0.199964,0.124223,0.342643,0.164813,0.566140,0.401677
2,0.202665,0.865867,0.474630,0.007429,0.735265,0.257795,0.259637,0.188507
3,0.038788,0.347467,0.730468,0.148946,0.017644,0.717699,0.891209,0.209200
4,0.551810,0.008895,0.674157,0.837020,0.412779,0.795796,0.176401,0.566522

In [59]:
dataF2['area']= dataF2['largo'] = dataF2['ancho']

SyntaxError: invalid character '√' (U+221A) (1588554183.py, line 1)

In [61]:
dataF2

,largo,ancho,prof,alt,masa,radio,vol,dens,area
0,0.710067,0.710067,0.185186,0.381147,0.495669,0.982155,0.201841,0.129467,0.710067
1,0.328919,0.328919,0.199964,0.124223,0.342643,0.164813,0.566140,0.401677,0.328919
2,0.865867,0.865867,0.474630,0.007429,0.735265,0.257795,0.259637,0.188507,0.865867
3,0.347467,0.347467,0.730468,0.148946,0.017644,0.717699,0.891209,0.209200,0.347467
4,0.008895,0.008895,0.674157,0.837020,0.412779,0.795796,0.176401,0.566522,0.008895