In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
suicides = pd.read_csv('suicides.csv')
suicides

,Year,State,Deaths,Population,Crude Rate,Age-Adjusted Rate,Years of Potential Life Lost
0,2020,Alabama,793,"4,921,532",16.11,15.91,"16,261"
1,2020,Alaska,204,"731,158",27.90,27.18,"5,460"
2,2020,Arizona,"1,363","7,421,401",18.37,17.63,"27,300"
3,2020,Arkansas,583,"3,030,522",19.24,19.15,"12,603"
4,2020,California,"4,144","39,368,078",10.53,9.98,"80,707"
...,...,...,...,...,...,...,...
1030,Race: All Races,NaN,NaN,NaN,NaN,NaN,NaN
1031,Ethnicity: All Ethnicities,NaN,NaN,NaN,NaN,NaN,NaN
1032,Metro / Non-Metro Indicator: None Selected,NaN,NaN,NaN,NaN,NaN,NaN
1033,YPLL Age: 65,NaN,NaN,NaN,NaN,NaN,NaN
1034,Produced by: National Center for Injury Preven...,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
read_file = pd.read_excel ("disasters.xlsx")

~/opt/anaconda3/lib/python3.9/site-packages/openpyxl/styles/stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [6]:
read_file.to_csv ("Test.csv", 
                  index = None,
                  header=True)

In [7]:
disasters = pd.DataFrame(pd.read_csv("Test.csv"))

In [8]:
disasters

,Source:,"EM-DAT, CRED / UCLouvain, Brussels, Belgium",Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 40,Unnamed: 41,Unnamed: 42,Unnamed: 43,Unnamed: 44,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49
0,NaN,www.emdat.be,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Version:,2023-05-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,File creation:,"Mon, 08 May 2023 19:13:26 CEST",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Table type:,Custom request,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,# of records:,1364,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365,2023-0032-USA,2023,0032,NaN,Natural,Meteorological,Storm,Convective storm,Tornado,NaN,...,NaN,NaN,NaN,715000,NaN,NaN,1,3214;3224,NaN,"Alabama, Georgia (Adm1)."
1366,2023-0176-USA,2023,0176,NaN,Natural,Meteorological,Storm,Convective storm,Tornado,NaN,...,NaN,NaN,NaN,10000,NaN,NaN,1;2,3214;3224;3256,30127;30141,"Alabama, Georgia, Tennessee (Adm1). Montgomery..."
1367,2023-0192-USA,2023,0192,NaN,Natural,Meteorological,Storm,Convective storm,Tornado,NaN,...,NaN,NaN,NaN,100000,NaN,NaN,1;2,3214;3217;3227;3229;3230;3231;3239;3249;3250;3...,28996;29434;29451,"Alabama, Arkansas, Illinois, Iowa, Kansas, Ken..."
1368,2023-0206-USA,2023,0206,NaN,Natural,Meteorological,Storm,Convective storm,Tornado,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,30169,Bollinger (Adm2).
1369,2023-0122-USA,2023,0122,NaN,Natural,Meteorological,Storm,Convective storm,NaN,NaN,...,NaN,NaN,NaN,4250000,NaN,NaN,1,3214;3217;3231;3232;3238;3250;3256;3257,NaN,"Alabama, Arkansas, Kentucky, Louisiana, Missis..."