# Pandas Data Structures - Cont

## Basic Math and Statistical Operations

In [1]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('ConfirmedFSMarch2023.csv')
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Confirmed FS Schedule,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Effective March 1, 2023 to March 31, 2023",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Origin,Dest.,Flight,Flight,Departure,Arrival,Aircraft,Subfleet,Effective,Discontinue
4,Airport,Airport,Number,Frequency,Time,Time,Type,Type,Date,Date
...,...,...,...,...,...,...,...,...,...,...
10628,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10629,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10630,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10631,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10632,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
aveHappi = df['HappinessScore'].sum()/len(df)
aveHappi

5.398907142857143

In [4]:
aveHappi =  df['HappinessScore'].mean()
aveHappi

5.3989071428571425

In [5]:
sum(df['HappinessScore'])/len(df)

5.3989071428571425

In [6]:
df.sum()

Country                              NorwayDenmarkIcelandSwitzerlandFinlandNetherla...
Region                               Western EuropeWestern EuropeWestern EuropeWest...
Rank                                                                              9870
HappinessScore                                                                 755.847
Life Ladder                                                                 768.838288
Log GDP per capita                                                         1242.966817
Social support                                                              112.132889
Healthy life expectancy at birth                                           8881.737408
Freedom to make life choices                                                108.124485
Generosity                                                                   -1.532985
Perceptions of corruption                                                    94.191357
Positive affect                                                              97.218274
Negative affect                                                              40.471861
Confidence in national government                                            62.700046
dtype: object

In [7]:
df.sum(axis = 1)

0      102.416253
1      103.363037
2      105.772921
3      107.245193
4      106.233556
          ...
135    207.313663
136    208.003508
137    208.802030
138    214.406951
139    194.532106
Length: 140, dtype: float64

In [8]:
df.Country.dtype

dtype('O')

In [10]:
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 140 entries, 0 to 139
Data columns (total 14 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   Country                            140 non-null    object
 1   Region                             140 non-null    object
 2   Rank                               140 non-null    int64
 3   HappinessScore                     140 non-null    float64
 4   Life Ladder                        140 non-null    float64
 5   Log GDP per capita                 133 non-null    float64
 6   Social support                     139 non-null    float64
 7   Healthy life expectancy at birth   140 non-null    float64
 8   Freedom to make life choices       139 non-null    float64
 9   Generosity                         132 non-null    float64
 10  Perceptions of corruption          128 non-null    float64
 11  Positive affect                    139 non-null    float64
 12  Negative affect                    139 non-null    float64
 13  Confidence in national government  127 non-null    float64
dtypes: float64(11), int64(1), object(2)
memory usage: 15.4+ KB

In [27]:
df.iloc[[0]].sum()
# df.iloc[0].sum() producirá error ya que tratará de sumar todos los valores de una sola fila (sumar todas las columnas en una fila, incluyendo strings con ints and floats)
# Si quiere sumar solamente los valores numéricos de una fila, debe hacer slicing:
# df.iloc[0, 2:].sum()

102.41625334699998

In [14]:
df.iloc[3:5].sum()
# loc for labels

Country                                        SwitzerlandFinland
Region                               Western EuropeWestern Europe
Rank                                                            9
HappinessScore                                             14.963
Life Ladder                                             15.261845
Log GDP per capita                                      21.567886
Social support                                           1.913488
Healthy life expectancy at birth                        144.87072
Freedom to make life choices                             1.887196
Generosity                                               0.155701
Perceptions of corruption                                0.508596
Positive affect                                          1.561134
Negative affect                                          0.371937
Confidence in national government                        1.417245
dtype: object

In [16]:
minIn = df['HappinessScore'].idxmin()
df.iloc[minIn]

Country                              Central African Republic
Region                                     Sub-Saharan Africa
Rank                                                      140
HappinessScore                                          2.693
Life Ladder                                          3.475862
Log GDP per capita                                        NaN
Social support                                       0.319589
Healthy life expectancy at birth                    44.645351
Freedom to make life choices                         0.645252
Generosity                                                NaN
Perceptions of corruption                            0.889566
Positive affect                                      0.613865
Negative affect                                      0.599335
Confidence in national government                    0.650285
Name: 139, dtype: object

In [17]:
df['HappinessScore']>5

0       True
1       True
2       True
3       True
4       True
       ...
135    False
136    False
137    False
138    False
139    False
Name: HappinessScore, Length: 140, dtype: bool

In [18]:
df.loc[df['HappinessScore']>5]
df[df['HappinessScore']>5]

,Country,Region,Rank,HappinessScore,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
0,Norway,Western Europe,1,7.537,7.578745,11.081789,0.950128,71.086586,0.953017,0.210104,0.249711,0.849100,0.202914,0.717160
1,Denmark,Western Europe,2,7.522,7.593702,10.748989,0.952100,71.662498,0.955416,0.145387,0.181148,0.823667,0.205775,0.572353
2,Iceland,Western Europe,3,7.504,7.476214,10.760409,0.966753,72.755981,0.938783,0.235479,0.726845,0.895255,0.148160,0.365042
3,Switzerland,Western Europe,4,7.494,7.473593,10.955548,0.949661,73.173759,0.924997,0.167875,0.316183,0.773997,0.195871,0.819707
4,Finland,Western Europe,5,7.469,7.788252,10.612338,0.963826,71.696960,0.962199,-0.012174,0.192413,0.787137,0.176066,0.597539
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,Macedonia,Central and Eastern Europe,85,5.175,5.233867,9.503636,0.799955,65.875778,0.752107,-0.062728,0.855697,0.502460,0.299391,0.442916
85,Nigeria,Sub-Saharan Africa,86,5.074,5.321928,8.585621,0.733469,45.873157,0.825906,0.113301,0.834892,0.724991,0.235969,0.558791
86,Vietnam,Southeast Asia,87,5.074,5.175279,8.742655,NaN,66.245766,NaN,NaN,NaN,NaN,NaN,NaN
87,Tajikistan,Commonwealth of Independent States,88,5.041,5.829234,7.956590,0.662693,62.971249,0.832002,0.124936,0.718337,0.602668,0.277725,0.929793
88,Kyrgyzstan,Commonwealth of Independent States,89,5.004,5.629537,8.112041,0.882587,62.899647,0.859390,0.166667,0.874494,0.755125,0.160438,0.561673

In [19]:
df.loc[df['HappinessScore']>5,['Region','Rank']]

                                Region  Rank
0                       Western Europe     1
1                       Western Europe     2
2                       Western Europe     3
3                       Western Europe     4
4                       Western Europe     5
..                                 ...   ...
84          Central and Eastern Europe    85
85                  Sub-Saharan Africa    86
86                      Southeast Asia    87
87  Commonwealth of Independent States    88
88  Commonwealth of Independent States    89

[89 rows x 2 columns]

In [23]:
df.loc[(df['HappinessScore']>5) & (df['Log GDP per capita']<8),['Region','Rank']]

                                Region  Rank
87  Commonwealth of Independent States    88

In [24]:
# Use al final ya que lo que devuelve no es el DF sino un "styler".
# df.style.set_properties(**{'text-align':'left'}).set_table_styles([dict(selector='th', props=[('text-align', 'left')])])